### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Charlie-robin** [ShivaniGanatra/Porfolio-Challenge#1]
# Feedback

## Requirements:

1. A deployed website (using GitHub Pages)
2. A public GitHub repository for your codebase
3. Use HTML & SCSS
4. Make good use of semantic HTML elements
5. Be responsive (mobile-first) and built with accessibility in mind
6. Code is highly readable (good naming and indented correctly)

## Score

[MARKING-SCHEME](https://github.com/nology-tech/Waiheke-Course-Resources/blob/main/student-resources/01-web/marking-scheme.md)

| Category             | Score    |
| -------------------- | -------- |
| Site Output          | 20 / 50  |
| Responsiveness       | 10 / 15  |
| Code Knowledge & Use | 10 / 20  |
| Readability          | 5 / 15   |
| Version Control      | 10 / 10  |
| Total Score          | 55 / 110 |

## Notes

Currently, your project is flagged as red, we will need to catch up and get a plan together.

### Positive

- You are using semantic tags so keep this up. Your tags need to describe the contents they are holding. Not everything needs to be a `<div>`.

- You have focused on mobile first and have created a responsive website, that works on desktop & mobile. Good going!
  - The Media queries in the `_components.scss` file are broken though see below.
- I can see the application of the content we have covered such as grid, and flex which is good but it is hit and miss and not consistent.

- The website on the surface looks good and almost matches the design. Unfortunately, the way you have achieved this is by using images from the wireframe rather than using your newly acquired knowledge of HTML and CSS/SCSS.

### Constructive

- Your BEM is a bit hit-and-miss and needs some work. Have a look at the examples and points below.

  - You generally don't name it as you have. You would have block or block__element or block__element--modifier and that is it. The example below starts with an element and then has an element and modifier tagged on.

```html
<!-- CURRENT CODE -->
<nav class="navigation__container">
  <a class="navigation__container__button" class="navigation__container__button--home" href="home">Home</a>
  <a class="navigation__container__button" class="navigation__container__button--about-me" href="#about-me">About</a>
  <a class="navigation__container__button" class="navigation__container__button--projects" href="#projects">Projects</a>
  <a
    class="navigation__container__button"
    class="navigation__container__button--get-in-touch"
    href="#get-in-touch-button"
  >
    <img
      class="navigation__container__button-getintouch"
      src="./Buttons/Type=Default.svg"
      alt="Get in Touch Button"
      href="#footer"
    />
  </a>
</nav>

<!-- COULD BE -->

<!-- THIS IS YOU BLOCK SO IF IT IS TWO WORDS IT IS HYPHENATED e.g navigation-container NOT navigation__container -->
<nav class="navigation-container">
  <!-- THESE ARE THE ELEMENTS SO IT WILL BE BLOCK__ELEMENT OR BLOCK__ELEMENT--MODIFIER -->
  <a class="navigation-container__button navigation-container__button--home" href="#home">Home</a>
  <!-- YOU CAN ADD MULTIPLE CLASSES BY ADD A SPACE BETWEEN EACH CLASS NAME -->
  <a class="navigation-container__button navigation-container__button--about-me" href="#about-me">About</a>
  <a class="navigation-container__button navigation-container__button--projects" href="#projects">Projects</a>
  <!-- THIS SHOULDN'T BE AN IMAGE YOU CAN STYLE THE HTML ELEMENT TO HAVE A BORDER AND BE BOLD -->
  <a class="navigation-container__button navigation-container__button--get-in-touch" href="#footer">Get In touch </a>
</nav>
```

- You want to avoid using any HTML as CSS selectors, the rule is everything that is going to have specific styles needs a class name. Resets are the exception.

```html
<!-- CURRENT CODE -->
<header>
  <div class="header--text">
    <h1>Hey I'm Shivani</h1>
    <h2>A Junior software developer based in the UK</h2>
  </div>
  <div class="header--image">
    <img src="./images/Picture (1).jpg" alt="bjhbjhb" />
  </div>
</header>

<!-- COULD BE -->
<header class="header">
  <div>
    <h1 class="header__title">Hey I'm Shivani</h1>
    <h2 class="header__sub-title">A Junior software developer based in the UK</h2>
  </div>
  <div>
    <img class="header__image" src="./images/Picture (1).jpg" alt="bjhbjhb" />
  </div>
</header>
```

```scss
// CURRENT STYLES
// - USING HTML SELECTORS
header {
  // ...

  h1 {
    // ...
  }

  h2 {
    // ...
  }

  img {
    // ...
  }
}

// COULD BE
// - USING BEM CLASS NAMES
.header {
  // ^^BLOCK
  // ...

  &__title {
    // ...
  }

  &__sub-title {
    // ...
  }

  &__image {
    // ...
  }
  // ^^ BLOCK__ELEMENTS
}
```

- You are using images for the project section this should be HTML with CSS to style it.
  - You have missed an opportunity to apply what we have covered here and without it, you do miss a large chunk of the design and application of content covered.
  - These should be HTML elements with styles.

```html
<!-- CURRENT CODE -->
<section id="projects" class="project-container">
  <img class="project-container--item" src="./project card/Project Card.svg" alt="Project card" />
  <!-- ... -->
</section>

<!-- COULD BE -->

<section id="projects" class="project-container">
  <div class="project-container__item">
    <img src="" alt="" />
    <p>REACT</p>
    <h3>Client Project</h3>
    <p>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius, officiis quis? Adipisci ipsam excepturi asperiores.
    </p>
    <div>
      <button>CODE</button>
      <button>PREVIEW</button>
    </div>
  </div>
  <!-- ... -->
</section>
```

- The media queries in the `_components.scss` are muddled & broken see notes below.

```scss
@media screen and (min-width:768px) {

    .project-container {
        justify-content: center;
        display: grid;
        grid-template-columns: 1fr 1fr 1fr;
        grid-template-rows: 1fr 1fr;
        gap: 10px;
        justify-content: center;
        padding-left: 60px;

    }

    .navigation__container {
        display: flex;
        justify-content: flex-end;
        flex-direction: row;
        align-items: flex-end;

        &__button {
            text-decoration: none;
            color: $secondary-color;
            padding: 11px 25px;
            border-radius: 4px;
            flex-direction: column;
        }

        &__button--projects:hover {
            background-color: aquamarine;
        }

// IT LOOKS LIKE YOU ARE MISSING THE CLOSING } FOR .navigation__container & THE MEDIA QUERY ABOVE ^

        @media screen and (min-width:1440px) {
            .technical-skill-icon-container {
                display: flex;
                flex-direction: row;
                align-items: center;
                justify-content: center;
            }

            .navigation__container {
                display: flex;
                justify-content: flex-end;
                flex-direction: row;
                align-items: flex-end;

                &__button {
                    text-decoration: none;
                    color: $tertiary-color;
                    padding: 11px 25px;
                    flex-direction: column;
                }

            }
        }
    } // YOU SHOULD BE ABLE TO REMOVE THIS } IF YOU HAVE ADDED THE ONES ABOVE
```

---
